# Generated by Django 3.0.4 on 2020-03-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, verbose_name='Name of Cheese'), unique=True),
        ),
    ]
