# Generated by Django 3.0.4 on 2020-04-01 00:54

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0005_cheese_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Cheese Address'),
        ),
    ]
